// swift-tools-version: 6.0
import PackageDescription

let package = Package(
    name: "JXL",
    platforms: [
        .macOS(.v13)
    ],
    products: [
        .library(name: "JXLCore", targets: ["JXLCore"]),
        .library(name: "JXLKit", targets: ["JXLKit"]),
        .executable(name: "jxl", targets: ["jxl"]),
    ],
    targets: [
        // Pure-Swift, from-scratch JPEG XL implementation. No dependency on libjxl.
        .target(
            name: "JXLCore"
        ),
        // CoreGraphics bridge (CGImage from decoded planes), shared by the
        // viewer app and the Quick Look extension. Keeps JXLCore Foundation-only.
        .target(
            name: "JXLKit",
            dependencies: ["JXLCore"]
        ),
        // Command-line front-end: `jxl info <file>`, `jxl boxes <file>`.
        .executableTarget(
            name: "jxl",
            dependencies: ["JXLCore"]
        ),
        .testTarget(
            name: "JXLCoreTests",
            dependencies: ["JXLCore"],
            resources: [
                // .jxl fixtures generated by libjxl's cjxl (used only as test inputs/oracle).
                .copy("Fixtures")
            ]
        ),
    ]
)
