import XCTest

@testable import JXLCore

final class HeaderTests: XCTestCase {

    /// Fixtures generated by libjxl's cjxl from PPMs of known size (see
    /// Tests/JXLCoreTests/Fixtures). Filenames encode ground-truth dimensions.
    static let sizes: [(w: UInt32, h: UInt32)] = [
        (1, 1), (3, 5), (17, 1), (64, 48), (100, 100), (640, 480), (513, 257),
    ]
    static let variants = ["lossless", "lossy", "container"]

    func fixtureURL(_ name: String) throws -> URL {
        let base = (name as NSString).deletingPathExtension
        let ext = (name as NSString).pathExtension
        guard
            let url = Bundle.module.url(
                forResource: base, withExtension: ext, subdirectory: "Fixtures")
        else {
            throw XCTSkip("fixture \(name) not bundled")
        }
        return url
    }

    func testDimensionsMatchAllFixtures() throws {
        for (w, h) in Self.sizes {
            for variant in Self.variants {
                let name = "\(w)x\(h)_\(variant).jxl"
                let url = try fixtureURL(name)
                let info = try JXL.readInfo(contentsOf: url)
                XCTAssertEqual(info.width, w, "width mismatch for \(name)")
                XCTAssertEqual(info.height, h, "height mismatch for \(name)")
            }
        }
    }

    func testContainerDetection() throws {
        let raw = try JXL.readInfo(contentsOf: fixtureURL("64x48_lossless.jxl"))
        XCTAssertFalse(raw.isContainer)
        XCTAssertTrue(raw.boxTypes.isEmpty)

        let container = try JXL.readInfo(contentsOf: fixtureURL("64x48_container.jxl"))
        XCTAssertTrue(container.isContainer)
        // A container file should at least carry the ftyp and a codestream box.
        XCTAssertTrue(container.boxTypes.contains("ftyp"))
        XCTAssertTrue(container.boxTypes.contains(where: { $0 == "jxlc" || $0 == "jxlp" }))
    }

    func testRejectsNonJXL() {
        XCTAssertThrowsError(try JXL.readInfo(from: [0x00, 0x01, 0x02, 0x03])) { error in
            XCTAssertEqual(error as? JXLError, .invalidSignature)
        }
    }

    func testImageMetadataFixtures() throws {
        let cases:
            [(
                name: String, bits: UInt32, exponentBits: UInt32, colorSpace: JXLColorSpace,
                alpha: Bool, extra: Int
            )] = [
                ("40x30_gray8.jxl", 8, 0, .grayscale, false, 0),
                ("40x30_rgba8.jxl", 8, 0, .rgb, true, 1),
                ("40x30_rgb16.jxl", 16, 0, .rgb, false, 0),
                ("40x30_rgbf32.jxl", 32, 8, .rgb, false, 0),
            ]

        for c in cases {
            let info = try JXL.readInfo(contentsOf: fixtureURL(c.name))
            XCTAssertEqual(info.width, 40, "width mismatch for \(c.name)")
            XCTAssertEqual(info.height, 30, "height mismatch for \(c.name)")
            XCTAssertEqual(info.bitDepth.bitsPerSample, c.bits, "bits mismatch for \(c.name)")
            XCTAssertEqual(
                info.bitDepth.exponentBitsPerSample, c.exponentBits,
                "exponent bits mismatch for \(c.name)")
            XCTAssertEqual(
                info.bitDepth.isFloatingPoint, c.exponentBits > 0, "float mismatch for \(c.name)")
            XCTAssertEqual(info.colorSpace, c.colorSpace, "color space mismatch for \(c.name)")
            XCTAssertEqual(info.hasAlpha, c.alpha, "alpha mismatch for \(c.name)")
            XCTAssertEqual(
                info.extraChannelCount, c.extra, "extra channel count mismatch for \(c.name)")
        }
    }

    func testSizeHeaderAspectRatioMath() {
        XCTAssertEqual(SizeHeader.width(forRatio: 3, height: 48), 64)  // 4:3
        XCTAssertEqual(SizeHeader.width(forRatio: 1, height: 100), 100)  // 1:1
        XCTAssertEqual(SizeHeader.width(forRatio: 7, height: 50), 100)  // 2:1
    }
}
